CREATE DATABASE avalia;

\c avalia;

CREATE TABLE animals (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    peso_real VARCHAR(100) NOT NULL
);

CREATE TABLE species (
    id SERIAL PRIMARY KEY,
    race VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    photo VARCHAR(255),
    animals_id INTEGER REFERENCES animals(id) ON DELETE SET NULL
);

INSERT INTO animals (name, peso_real) VALUES
    ('Belinha', '4kg'),
    ('Luna', '5kg'),
    ('Estrela', '4.5kg'),
    ('Tobias', '4kg'),
    ('Chunica', '5kg'),
    ('Thor', '34kg'),
    ('Pedrita', '9kg'),
    ('Charmosa', '30kg'),
    ('Bob', '3kg'),
    ('Milo', '6kg'),
    ('Nina', '7kg'),
    ('Simba', '4.2kg'),
    ('Max', '8kg'),
    ('Tom', '3.9kg'),
    ('Jerry', '2.8kg'),
    ('Lili', '3.5kg'),
    ('Mel', '4.7kg'),
    ('Dudu', '2.9kg'),
    ('Zeus', '15kg'),
    ('Apolo', '13kg'),
    ('Athena', '12kg'),
    ('Pipoca', '2.6kg'),
    ('Frajola', '6.3kg'),
    ('Bidu', '7.5kg'),
    ('Snoopy', '9.2kg'),
    ('Pitoco', '10kg'),
    ('Tico', '1.5kg'),
    ('Teco', '1.4kg'),
    ('Fiona', '5.1kg'),
    ('Shrek', '32kg'),
    ('Bolinha', '6.6kg'),
    ('Pingo', '7.7kg'),
    ('Lola', '5.5kg'),
    ('Dora', '4.1kg'),
    ('Lulu', '3.3kg'),
    ('Bento', '8.8kg'),
    ('Tigrão', '11kg'),
    ('Gato', '3.8kg'),
    ('Dog', '20kg'),
    ('Rex', '25kg'),
    ('Lorde', '29kg'),
    ('Princesa', '4.3kg'),
    ('Duque', '17kg'),
    ('Rainha', '6.4kg'),
    ('Rei', '18kg'),
    ('Lady', '7.9kg'),
    ('Bruce', '22kg'),
    ('Rocky', '28kg'),
    ('Spike', '19kg'),
    ('Fofinho', '2.1kg'),
    ('Bela', '3.7kg'),
    ('Sol', '2.8kg'),
    ('Lua', '4.3kg'),
    ('Estrela2', '4.9kg'),
    ('Nuvem', '5.8kg'),
    ('Mar', '6.2kg'),
    ('Rio', '5.4kg'),
    ('Lago', '8.2kg'),
    ('Montanha', '9.5kg'),
    ('Vale', '7.1kg'),
    ('Floresta', '14kg'),
    ('Campo', '15kg'),
    ('Selva', '16kg'),
    ('Bosque', '8.6kg'),
    ('Praia', '13kg'),
    ('Areia', '12kg'),
    ('Pedra', '11.2kg'),
    ('Rocha', '10.9kg'),
    ('Vento', '4.2kg'),
    ('Tempestade', '5.5kg'),
    ('Chuva', '3.3kg'),
    ('Neve', '2.8kg'),
    ('Granizo', '1.6kg'),
    ('Gelo', '1.8kg'),
    ('Fogo', '2.2kg'),
    ('Luz', '3.1kg'),
    ('Sombra', '2.5kg'),
    ('Treva', '2.9kg'),
    ('Nina2', '7kg'),
    ('Simba2', '4.4kg'),
    ('Max2', '8.4kg'),
    ('Tom2', '3.7kg'),
    ('Jerry2', '2.6kg'),
    ('Lili2', '3.9kg'),
    ('Mel2', '4.5kg'),
    ('Dudu2', '2.7kg'),
    ('Zeus2', '14kg'),
    ('Apolo2', '13.3kg'),
    ('Athena2', '12.1kg'),
    ('Pipoca2', '2.9kg'),
    ('Frajola2', '6.7kg'),
    ('Bidu2', '7.8kg'),
    ('Snoopy2', '9.4kg'),
    ('Pitoco2', '10.2kg'),
    ('Tico2', '1.8kg'),
    ('Teco2', '1.6kg'),
    ('Fiona2', '5.4kg'),
    ('Shrek2', '33kg'),
    ('Bolinha2', '6.9kg'),
    ('Pingo2', '7.8kg'),
    ('Lola2', '5.7kg'),
    ('Dora2', '4.4kg');

INSERT INTO species (race, description, animals_id) VALUES
    ('Siamês', 'Dócil e fértil', 1),
    ('Persa', 'Dócil e fértil', 2),
    ('Tonquinês', 'Nada amigavel', 3),
    ('Mist australiano', 'Dócil e castrado', 4),
    ('Balinês', 'Dócil e castrado', 5),
    ('Golden retriever', 'amigo de todos e castrado', 6),
    ('Beagle', 'Amigo de todos, castrado e para brincar morde', 7),
    ('Poodle', 'Não é amigavel, fertil', 8),
    ('Pinscher', 'Não é amigavel, SE AFASTE', 9),
     ('SRD', 'Manso', 10),
    ('SRD', 'Arisco', 11),
    ('Sphynx', 'Muito dócil', 12),
    ('Angorá', 'Peludo e brincalhão', 13),
    ('Exótico', 'Quieto', 14),
    ('Himalaio', 'Amoroso', 15),
    ('Savannah', 'Curioso', 16),
    ('Maine Coon', 'Grande e dócil', 17),
    ('Ragdoll', 'Calmo', 18),
    ('Buldogue', 'Dorminhoco', 19),
    ('Boxer', 'Ativo', 20),
    ('Chihuahua', 'Latidor', 21),
    ('Labrador', 'Muito brincalhão', 22),
    ('Dálmata', 'Ativo e bonito', 23),
    ('Pastor Alemão', 'Inteligente', 24),
    ('Shih-tzu', 'Peludo e amoroso', 25),
    ('Yorkshire', 'Pequeno e valente', 26),
    ('Pug', 'Engraçado', 27),
    ('Bulldog Francês', 'Amoroso', 28),
    ('Spitz Alemão', 'Fofo', 29),
    ('Basset', 'Companheiro', 30),
    ('Doberman', 'Valente', 31),
    ('Cocker', 'Faminto', 32),
    ('Akita', 'Leal', 33),
    ('Husky', 'Agitado', 34),
    ('Samoyeda', 'Peludo', 35),
    ('Shiba', 'Esperto', 36),
    ('Setter', 'Atleta', 37),
    ('Weimaraner', 'Elegante', 38),
    ('Fox Paulistinha', 'Pequeno', 39),
    ('Fila', 'Protetor', 40),
    ('Mastiff', 'Enorme', 41),
    ('Lhasa Apso', 'Fofo', 42),
    ('Papillon', 'Pequeno', 43),
    ('Cavalier', 'Carinhoso', 44),
    ('Boston Terrier', 'Ativo', 45),
    ('Border Collie', 'Inteligente', 46),
    ('Whippet', 'Rápido', 47),
    ('Basenji', 'Silencioso', 48),
    ('Dogue Alemão', 'Gigante', 49),
    ('Chow Chow', 'Peludo', 50),
    ('SRD', 'Manso', 51),
    ('SRD', 'Arisco', 52),
    ('Sphynx', 'Muito dócil', 53),
    ('Angorá', 'Peludo e brincalhão', 54),
    ('Exótico', 'Quieto', 55),
    ('Himalaio', 'Amoroso', 56),
    ('Savannah', 'Curioso', 57),
    ('Maine Coon', 'Grande e dócil', 58),
    ('Ragdoll', 'Calmo', 59),
    ('Buldogue', 'Dorminhoco', 60),
    ('Boxer', 'Ativo', 61),
    ('Chihuahua', 'Latidor', 62),
    ('Labrador', 'Muito brincalhão', 63),
    ('Dálmata', 'Ativo e bonito', 64),
    ('Pastor Alemão', 'Inteligente', 65),
    ('Shih-tzu', 'Peludo e amoroso', 66),
    ('Yorkshire', 'Pequeno e valente', 67),
    ('Pug', 'Engraçado', 68),
    ('Bulldog Francês', 'Amoroso', 69),
    ('Spitz Alemão', 'Fofo', 70),
    ('Basset', 'Companheiro', 71),
    ('Doberman', 'Valente', 72),
    ('Cocker', 'Faminto', 73),
    ('Akita', 'Leal', 74),
    ('Husky', 'Agitado', 75),
    ('Samoyeda', 'Peludo', 76),
    ('Shiba', 'Esperto', 77),
    ('Setter', 'Atleta', 78),
    ('Weimaraner', 'Elegante', 79),
    ('Fox Paulistinha', 'Pequeno', 80),
    ('Fila', 'Protetor', 81),
    ('Mastiff', 'Enorme', 82),
    ('Lhasa Apso', 'Fofo', 83),
    ('Papillon', 'Pequeno', 84),
    ('Cavalier', 'Carinhoso', 85),
    ('Boston Terrier', 'Ativo', 86),
    ('Border Collie', 'Inteligente', 87),
    ('Whippet', 'Rápido', 88),
    ('Basenji', 'Silencioso', 89),
    ('Dogue Alemão', 'Gigante', 90),
    ('Chow Chow', 'Peludo', 91),
    ('SRD', 'Manso', 92),
    ('SRD', 'Arisco', 93),
    ('Sphynx', 'Muito dócil', 94),
    ('Angorá', 'Peludo e brincalhão', 95),
    ('Exótico', 'Quieto', 96),
    ('Himalaio', 'Amoroso', 97),
    ('Savannah', 'Curioso', 98),
    ('Maine Coon', 'Grande e dócil', 99),
    ('Ragdoll', 'Calmo', 100);